// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeOAl9YgPK5uSmiZ7m3Hs6gFgV3HKBkMg',
    appId: '1:598395567919:web:bb65bb414274b1bb702bda',
    messagingSenderId: '598395567919',
    projectId: 'novo-app-flattrade',
    authDomain: 'novo-app-flattrade.firebaseapp.com',
    storageBucket: 'novo-app-flattrade.firebasestorage.app',
    measurementId: 'G-WZHBDQ2JHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDM04UIi73psmxXX_nxjZxnxwNn3hvyME',
    appId: '1:598395567919:android:94f9cc9a055fb0a0702bda',
    messagingSenderId: '598395567919',
    projectId: 'novo-app-flattrade',
    storageBucket: 'novo-app-flattrade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVQJXcdA7yVxbIEcMmj4vBJ7h5vDllnFU',
    appId: '1:598395567919:ios:bbae06e79dae656b702bda',
    messagingSenderId: '598395567919',
    projectId: 'novo-app-flattrade',
    storageBucket: 'novo-app-flattrade.firebasestorage.app',
    iosBundleId: 'com.flattrade.novo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVQJXcdA7yVxbIEcMmj4vBJ7h5vDllnFU',
    appId: '1:598395567919:ios:02c4d6c8074ed0bc702bda',
    messagingSenderId: '598395567919',
    projectId: 'novo-app-flattrade',
    storageBucket: 'novo-app-flattrade.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeOAl9YgPK5uSmiZ7m3Hs6gFgV3HKBkMg',
    appId: '1:598395567919:web:2fa8a0892de8160c702bda',
    messagingSenderId: '598395567919',
    projectId: 'novo-app-flattrade',
    authDomain: 'novo-app-flattrade.firebaseapp.com',
    storageBucket: 'novo-app-flattrade.firebasestorage.app',
    measurementId: 'G-V5XDPVDTET',
  );

}