version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.18
    commands:
      - echo Installing dependencies...
      - go mod download
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 837305378307.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=837305378307.dkr.ecr.ap-south-1.amazonaws.com/fcs_263_instakyc_api_preprod
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo $IMAGE_TAG
      - echo $REPOSITORY_URI

  build:
    commands:
      - echo Building the Go application...
      - mkdir -p bin
      - go build -o bin/main main.go
      - echo logging into docker....
      - echo "dckr_pat_iEIGMex8SOsyKsllhhLUYhJskj4" | docker login -u lakshmananak --password-stdin      
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG  .

  post_build:
    commands:
      - echo Pushing the latest Docker image to ECR....
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"fcs_263_instakyc_api_preprod","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes

cache:
  paths:
    - /root/.cache/go-build
    - /go/pkg/mod
