# crmdealconfig

ZOHOCRMDEALURL = "http://192.168.150.21:29091/synccrm"
ZOHOCRMDEALNRIURL = "ZOHOCRMDEALNRIURL"

InformCRM="NO"
CRMDeal="uat"
#CRMDeal="prod"

STAGE_PHONE = "PHONE_VERIFIED"
STAGE_EMAIL = "EMAIL_VERIFIED"
STAGE_PAN = "PAN_VERFIFIED"
STAGE_ADDRESS = "ADDRESS_CAPTURED"
STAGE_BANK = "BANK_CAPTURED"
STAGE_SEGMENT = "SEGMENT_SELECTED"
STAGE_DOCUMENT = "DOCUMENT_UPLOADED"
STAGE_IPV = "IPV_COMPLETED"


STAGE_REJECTED = "VALIDATION_REJECTED"
STAGE_INPROGRESS = "VALIDATION_INPROGRESS"
STAGE_COMPLETED = "COMPLETED"