TariffDetailUrl = "FCS_263_DP_Tariff_pdf"

# Default Values
CitizeShip = "Indian"
Residential = "RESIDENT INDIVIDUAL"
EmpName = "DIVYA"
EmpCKYCcode = "IN0327"
EmpId = "ST95"
#EmpDes = "Authorized Person"
EmpDes = "Employee"
SMSOrEmail = "BOTH"
FacMode = "ELECTRONIC"
FacAvil = "Yes"
StockProfile = "NIL"
StockBroker = "N/A"
SubStockBroker = "N/A"
SubStockBroker2 = "N/A"
UCC = "N/A"
TradeExchange = "N/A"
TradeOtherData = "N/A"
NetWorth = "N/A"
NetWorthDate = "N/A"
ForeignMoneyChange = "No"
Gamblier = "No"
MoneyLending = "No"
TAXResident = "No"
Identification1 = "N/A"
Identification2 = "N/A"
AccountStatus = "Individual"
AccountSubStatusWithNominee = "Individual Resident"
AccountSubStatusWithOutNominee = "Individual Resident Negative Nominee"
Nationality = "INDIAN"
DefaultUID = "N/A"
DefaultPan = "N/A"
DefaultName = "N/A"
CDSLACCountStatement = "AS PER SEBI"
DPCredit = "YES"
ECS = "ELECTRONIC"
EmailAlert = "YES"
SMSAlert = "YES"
DPAccept = "YES"
RTA = "YES"
AnnualReport = "ELECTRONIC"
DepositoryServices = "ELECTRONIC"
NSECode = "14572"
BSECode = "6524"
DPNAME = "FCSPL"
ClientCode = ""
TMCode = "00231833"
CMCode = "00221204"
CMSegment = "YES"
RmsignDocID="18608"
AccountType="newkyc"
ballotBoxCheck="\\u9745  "
ballotBoxUnCheck="\\u9744  "
CDSLGUardian="N/A"
CDSLRelationship="N/A"
CDSLPAN="N/A"
UPI="N/A"
application_Charge="Rs: 200/- plus GST"
ReName="N/A"
ReType="N/A"
RePan="N/A"
DepoName="N/A"
DepoAccSub="N/A"
AlBoId="N/A"
AlDpId="N/A"

MobCode="+91"
IntermediatryName="Fortune Capital Services Private Limited"

# Nominee opt out configuration
NomineeOpted ="N"

# DIS and EDIS description
DISDescription ="Delivery Instruction Slip (DIS) is a form that investors need to fill for the offline transfer of shares from one Demat account to another"
EDISDescription ="Electronic Delivery Instruction Slip (EDIS) is a facility that allows you to sell shares if you have not submitted your Power of Attorney (POA), <a target='_blank'  href='https://flattrade.in/kosh/what-is-edis-and-how-to-use-it/'>know more</a>"

# Allow edit option to all

AllEditOpt="Y"