# filename: ifscconfig.toml

# ======================================================================================= 
#                                     LOCAL
# ======================================================================================= 

#IfscURL = "http://192.168.70.52:28029/getIfscBankDetails"

IfscURL = "https://razorpaysrv.flattrade.in/getIfscBankDetails"
