// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf6Y0ZQ2r0XCv-2F9u9B2jjaIJAib-jxo',
    appId: '1:693323865587:web:758e05a78c9c65b6b78686',
    messagingSenderId: '693323865587',
    projectId: 'ekyc-d1471',
    authDomain: 'ekyc-d1471.firebaseapp.com',
    storageBucket: 'ekyc-d1471.firebasestorage.app',
    measurementId: 'G-X26CGM5CKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM7TPyKj_pxU6GvMHhURTeOGHdjJfuCos',
    appId: '1:693323865587:android:db470d7db3707183b78686',
    messagingSenderId: '693323865587',
    projectId: 'ekyc-d1471',
    storageBucket: 'ekyc-d1471.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDucx4FFiJe_MOqChyzrrayKYI9XJ2aqzo',
    appId: '1:693323865587:ios:6470693882148b42b78686',
    messagingSenderId: '693323865587',
    projectId: 'ekyc-d1471',
    storageBucket: 'ekyc-d1471.firebasestorage.app',
    iosBundleId: 'com.flattrade.ekyc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDucx4FFiJe_MOqChyzrrayKYI9XJ2aqzo',
    appId: '1:693323865587:ios:6470693882148b42b78686',
    messagingSenderId: '693323865587',
    projectId: 'ekyc-d1471',
    storageBucket: 'ekyc-d1471.firebasestorage.app',
    iosBundleId: 'com.flattrade.ekyc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf6Y0ZQ2r0XCv-2F9u9B2jjaIJAib-jxo',
    appId: '1:693323865587:web:3b25477cec85f129b78686',
    messagingSenderId: '693323865587',
    projectId: 'ekyc-d1471',
    authDomain: 'ekyc-d1471.firebaseapp.com',
    storageBucket: 'ekyc-d1471.firebasestorage.app',
    measurementId: 'G-FMXSJSQ2GG',
  );

}