// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6bF1D7EeKiPL_c64YcG-zoEzr96qFS6w',
    appId: '1:805956353454:web:84669ab74c004087319c3f',
    messagingSenderId: '805956353454',
    projectId: 'instakyc-96517',
    authDomain: 'instakyc-96517.firebaseapp.com',
    storageBucket: 'instakyc-96517.appspot.com',
    measurementId: 'G-X8R3TNN4E1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmFMPQiWbVFW_aCvGGZIQK-bb2SdmlTDE',
    appId: '1:805956353454:android:493c64ecbce7fcfd319c3f',
    messagingSenderId: '805956353454',
    projectId: 'instakyc-96517',
    storageBucket: 'instakyc-96517.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrQ2dnsVHG50Anv1uwqJkcb_pLpQ-j5_4',
    appId: '1:805956353454:ios:743cc871ce26dad7319c3f',
    messagingSenderId: '805956353454',
    projectId: 'instakyc-96517',
    storageBucket: 'instakyc-96517.appspot.com',
    iosBundleId: 'com.flattrade.ekyc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrQ2dnsVHG50Anv1uwqJkcb_pLpQ-j5_4',
    appId: '1:805956353454:ios:743cc871ce26dad7319c3f',
    messagingSenderId: '805956353454',
    projectId: 'instakyc-96517',
    storageBucket: 'instakyc-96517.appspot.com',
    iosBundleId: 'com.flattrade.ekyc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6bF1D7EeKiPL_c64YcG-zoEzr96qFS6w',
    appId: '1:805956353454:web:0dddb7fdf0849e74319c3f',
    messagingSenderId: '805956353454',
    projectId: 'instakyc-96517',
    authDomain: 'instakyc-96517.firebaseapp.com',
    storageBucket: 'instakyc-96517.appspot.com',
    measurementId: 'G-XLTFDGMY3D',
  );

}