INSERT INTO coresettings (KEYV,VALUEV,Enabled,createdBy,createdProgram,createdDate,updatedBy,updatedProgram,updatedDate) VALUES
	 ('CDSL_NSE_CMID','M51880',1,'ayyanar.b@fcsonline.co.in','FLOW',now(),'ayyanar.b@fcsonline.co.in','FLOW',now()),
	 ('CDSL_BSE_CMID','M51880',1,'ayyanar.b@fcsonline.co.in','FLOW',now(),'ayyanar.b@fcsonline.co.in','FLOW',now()),
	 ('CDSL_MCX_CMID','16765',1,'ayyanar.b@fcsonline.co.in','FLOW',now(),'ayyanar.b@fcsonline.co.in','FLOW',now()),
	 ('CDSL_MCX_TMID','16765',1,'ayyanar.b@fcsonline.co.in','FLOW',now(),'ayyanar.b@fcsonline.co.in','FLOW',now()),
	 ('CDSL_NSE_TMID','14572',1,'ayyanar.b@fcsonline.co.in','FLOW',now(),'ayyanar.b@fcsonline.co.in','FLOW',now()),
	 ('CDSL_BSE_TMID','6524',1,'ayyanar.b@fcsonline.co.in','FLOW',now(),'ayyanar.b@fcsonline.co.in','FLOW',now()),
	 ('FCS_94_DDPI_Auth_Token','6bafdf50-c1be-4333-9868-2dc3478d6e5e',1,'ayyanar.b@fcsonline.co.in','FLOW',now(),'thineshgunal.v@fcsonline.co.in','FLOW',now()),
	 ('FCS_263_fromEmail','info-noreply@mailer.flattrade.in',1,'lakshmanan.ak@flattrade.in','Flow',now(),'lakshmanan.ak@flattrade.in','Flow',now()),
	 ('FCS_263_fromDspName','Autobot',1,'lakshmanan.ak@flattrade.in','Flow',now(),'lakshmanan.ak@flattrade.in','Flow',now()),
	 ('FCS_263_toEmail','appsupport@flattrade.in',1,'lakshmanan.ak@flattrade.in','Flow',now(),'lakshmanan.ak@flattrade.in','Flow',now()),
	 ('FCS_263_emailServer','ftctrade.co.in',1,'lakshmanan.ak@flattrade.in','Flow',now(),'lakshmanan.ak@flattrade.in','Flow',now()),
	 ('FCS_263_replyTo','appsupport@flattrade.in',1,'lakshmanan.ak@flattrade.in','Flow',now(),'lakshmanan.ak@flattrade.in','Flow',now()),
	 ('FCS_263_EmailSubject','Insta KYC API Error as on ',1,'lakshmanan.ak@flattrade.in','Flow',now(),'lakshmanan.ak@flattrade.in','Flow',now()),
	 ('FCS_263_OTPSubject','OTP for Flattrade AOF',1,'lakshmanan.ak@flattrade.in','Flow',now(),'lakshmanan.ak@flattrade.in','Flow',now()),
	 ('FCS_263_IPVSubject','Complete your IPV!',1,'lakshmanan.ak@flattrade.in','Flow',now(),'lakshmanan.ak@flattrade.in','Flow',now()),
	 ('FCS_263_FormCompleteSubject',"You're all set for your Flattrade account!",1,'lakshmanan.ak@flattrade.in','Flow',now(),'lakshmanan.ak@flattrade.in','Flow',now()),
	 ('FCS_263_RejectSubject','Flattrade form is rejected!',1,'lakshmanan.ak@flattrade.in','Flow',now(),'lakshmanan.ak@flattrade.in','Flow',now()),
	 ('FCS_263_startHr','0',1,'lakshmanan.ak@flattrade.in','Flow',now(),'lakshmanan.ak@flattrade.in','Flow',now()),
	 ('FCS_263_endHr','23',1,'lakshmanan.ak@flattrade.in','Flow',now(),'lakshmanan.ak@flattrade.in','Flow',now());