INSERT INTO lookup_header
(id, Code, description, Attr1, Attr2, Attr3, Attr4, Attr5, Attr6, Attr7, Attr8, Attr9, Attr10, createdDate, updatedDate, createdBy, updatedBy)
VALUES
(1, 'state', 'state Name', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(2, 'Client Type', 'Client Type', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(3, 'Nationality', 'Nationality', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(4, 'Nationality (Others)', 'Nationality (Others)', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(5, 'Gender', 'Gender', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(6, 'MarritalStatus', 'MarritalStatus', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(7, 'Client Transcation mode', 'Client Transcation mode', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(8, 'Client(Acctype)', 'Client(Acctype)', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(9, 'YN-Flag', 'YN-Flag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(10, 'Bank Account Type', 'Bank Account Type', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(11, 'AnnualIncome', 'AnnualIncome', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(12, 'Occupation', 'Occupation', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(13, 'NomineeOpted', 'NomineeOpted', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(14, 'Proof of Identity', 'Proof of Identity', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(15, 'PanExempt(ProofType)', 'PanExempt(ProofType)', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(16, 'KRA code', 'KRA code', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(17, 'Exempt Category', 'Exempt Category', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(18, 'Residential status (I)', 'Residentaial status (I)', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(19, 'Residential Address Proof (NRI)', 'Residentaial status (NRI)', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(20, 'AddressProof', 'AddressProofType', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(21, 'Politically Exposed', 'Politically Exposed', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(22, 'Document Submission Details', 'Document Submission Details', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(23, 'KYC mode', 'KYC mode', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(24, 'SameAsPermanentAddress', 'SameAsPermanentAddress', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(25, 'Type of Service', 'Type of Service', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(26, 'Contact Details', 'Contact Details', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(27, 'Depository Name', 'Depository Name', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(28, 'Provide Details', 'Provide Details', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(29, 'Client Status', 'Client Status', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(30, 'Opted upi', 'Opted upi', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(31, 'Segment Indicator', 'Segment Indicator', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(32, 'Cash Segment Flag', 'Cash Segment Flag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(33, 'SLB Segment Flag', 'SLB Segment Flag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(34, 'F&O Segment Flag', 'F&O Segment Flag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(35, 'CURRENCY Segment Flag', 'CURRENCY Segment Flag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(36, 'DEBT Segment Flag', 'DEBT Segment Flag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(37, 'EGR Segment Flag', 'EGR Segment Flag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(38, 'Commodity Segment Flag', 'Commodity Segment Flag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(39, 'Eduaction', 'EducationQualification', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(40, 'Client Title', 'Client Title', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(41, 'EFT', 'EFT', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(42, 'Communication mode', 'Communication mode', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(43, 'MobileEmailOwner', 'MobileEmailOwner', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(44, 'Introduced by', 'Introduced by', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(45, 'country', 'Country name', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(46, 'Account Open Location', 'Account Open Location', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(47, 'NRI Type', 'NRI Type', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(48, 'RiskCategroy', 'RiskCategroy', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(49, 'Company Status', 'Company Status', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(50, 'IPV Flag', 'IPV Flag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(51, 'KRA District code', 'KRA District code', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(52, 'BO Sub Status code', 'BO Sub Status code', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(53, 'Primary ISD code', 'Primary ISD code', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(54, 'PAN Exemption Code', 'PAN Exemption Code', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(55, 'Request received type(CDSL)', 'Request received type(CDSL)', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(56, 'Pan Verification code', 'Pan Verification code', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(57, 'UID Verification code', 'UID Verification code', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(58, 'Mode of operation', 'Mode of operation', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(59, 'Communication flag', 'Communication flag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(60, 'Geographical code', 'Geographical code', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(61, 'Language code', 'Language code', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(62, 'Staff / Relative', 'Staff / Relative', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(63, 'BO Category', 'BO Category', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(64, 'Currency', 'Currency', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(65, 'Nominee Relationship', 'Nominee Relationship', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(66, 'GPA / BPA', 'GPA / BPA', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(67, 'consent flag', 'consent flag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(68, 'Exchange Id', 'Exchange Id', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(69, 'Beneficiary Tax Deduction Status', 'Beneficiary Tax Deduction Status', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(70, 'IncomeProof', 'IncomeProofType', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(71, 'TradingExp', 'TradingExp', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(72, 'nomineeGuardianRelationship', 'nomineeGuardianRelationship', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(73, 'Pan service status', 'Pan service status', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(74, 'DematData', 'DematData', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(75, 'NewekycTableStatus', 'NewekycTableStatus', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(76, 'PANRequestStatus', 'PANRequestStatus', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(77, 'KYC status', 'KYC status', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(78, 'Power of Attorney (POA)', 'Power of Attorney (POA)', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(79, 'POA for Funds', 'POA for Funds', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(80, 'POA for Securities', 'POA for Securities', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(81, 'PrimaryOrSecondaryType', 'PrimaryOrSecondaryType', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(82, 'PanCopyFlag', 'PanCopyFlag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(83, 'PanExemptFlag', 'PanExemptFlag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(84, 'SmartRegistration', 'SmartRegistration', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(85, 'DematA/cFlag', 'DematA/cFlag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(86, 'RGESS Flag', 'RGESS Flag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(87, 'Email RTA Download Flag', 'Email RTA Download Flag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(88, 'Pledge Standing Instruction Flag', 'Pledge Standing Instruction Flag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(89, 'Email Statement Flag', 'Email Statement Flag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(90, 'Mental Disability Flag', 'Mental Disability Flag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(91, 'BO Settlement Planning Flag', 'BO Settlement Planning Flag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(92, 'ECS/Mandate', 'ECS/Mandate', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(93, 'Confirmation Waived', 'Confirmation Waived', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(94, 'Bonafide Flag', 'Bonafide Flag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(95, 'Residual Security Flag', 'Residual Security Flag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(96, 'Client Special Category', 'Client Special Category', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(97, 'DDPI PayIn', 'DDPI PayIn', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(98, 'DDPI Mutual Fund', 'DDPI Mutual Fund', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(99, 'DDPI Buy Back', 'DDPI Buy Back', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(100, 'DDPI Margin Pledge', 'DDPI Margin Pledge', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(101, 'UpdationFlag', 'UpdationFlag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(102, 'Dump Type', 'Dump Type', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(103, 'IBT_Scheme', 'IBT_Scheme', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(104, 'IBT_Client', 'IBT_Client', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(105, 'IBT_Charges_Debit_to', 'IBT_Charges_Debit_to', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(106, 'MTF_Client', 'MTF_Client', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(107, 'MTF_Client_Auto_Funding', 'MTF_Client_Auto_Funding', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(108, 'Charges', 'Charges', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(109, 'Dr._To', 'Dr._To', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(110, 'Internet_Trading', 'Internet_Trading', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(111, 'Statement_Option', 'Statement_Option', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(112, 'UCC_Flag', 'UCC_Flag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(113, 'NSEFO_Margin', 'NSEFO_Margin', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(114, 'PrintBill', 'PrintBill', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(115, 'PrintContract', 'PrintContract', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(116, 'FundTransfer', 'FundTransfer', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(117, 'Show_Confidential_Client_Data', 'Show_Confidential_Client_Data', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(118, 'Stock_Request', 'Stock_Request', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(119, 'Payment_Request', 'Payment_Request', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(120, 'Consider_SOH_In_Margin_Reporting', 'Consider_SOH_In_Margin_Reporting', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(121, 'CSV_Export_Format', 'CSV_Export_Format', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(122, 'CSV_Export_Format(FO)', 'CSV_Export_Format(FO)', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(123, 'ContractPrinting', 'ContractPrinting', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(124, 'Client_With_Custodian_Trade', 'Client_With_Custodian_Trade', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(125, 'Delivery_Type', 'Delivery_Type', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(126, 'Default_Ben', 'Default_Ben', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(127, 'Retention_Authorized_Letter', 'Retention_Authorized_Letter', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(128, 'SMS_Send', 'SMS_Send', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(129, 'Brk_in_Avg_Rate', 'Brk_in_Avg_Rate', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(130, 'Grp1_Active', 'Grp1_Active', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(131, 'Grp2_Active', 'Grp2_Active', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(132, 'Grp1_Inactive_Reason', 'Grp1_Inactive_Reason', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(133, 'Grp2_Inactive_Reason', 'Grp2_Inactive_Reason', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(134, 'Inst_Contract_No', 'Inst_Contract_No', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(135, 'Obl._Paid_By_Cust', 'Obl._Paid_By_Cust', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(136, 'Type_of_Client', 'Type_of_Client', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(137, 'Cust._Clearing_Client', 'Cust._Clearing_Client', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(138, 'SMS_Charges', 'SMS_Charges', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(139, 'NRI_Client_With_PIS', 'NRI_Client_With_PIS', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(140, 'Sharing_Type', 'Sharing_Type', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(141, 'Reward_Points', 'Reward_Points', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(142, 'Grp1_Charge_Apply', 'Grp1_Charge_Apply', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(143, 'Grp1_Charge_Option', 'Grp1_Charge_Option', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(144, 'Grp2_Charge_Apply', 'Grp2_Charge_Apply', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(145, 'Grp2_Charge_Option', 'Grp2_Charge_Option', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(146, 'Web_Login_Access', 'Web_Login_Access', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(147, 'E-Statement(Webx)', 'E-Statement(Webx)', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(148, 'Calc.Interest_Period', 'Calc.Interest_Period', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(149, 'Interest_Dr._To', 'Interest_Dr._To', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(150, 'No._of_Days', 'No._of_Days', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(151, 'Ben._To_Market_Charges', 'Ben._To_Market_Charges', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(152, 'Ben._To_Client_Charges', 'Ben._To_Client_Charges', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(153, 'Ben._Inward_Charges', 'Ben._Inward_Charges', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(154, 'Inter_Settlement_Charges', 'Inter_Settlement_Charges', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(155, 'Pool_Hold_Charges', 'Pool_Hold_Charges', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(156, 'Ben._Hold_Charges', 'Ben._Hold_Charges', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(157, 'Payout_From_Beneficiary', 'Payout_From_Beneficiary', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(158, 'Nach_Flag', 'Nach_Flag', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(159, 'Cross_Margin', 'Cross_Margin', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(160, 'Family_Head', 'Family_Head', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(161, 'Trust_Base_Payin_[CDSL]', 'Trust_Base_Payin_[CDSL]', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(162, 'Payment_to_Release', 'Payment_to_Release', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(163, 'KRA_Status', 'KRA_Status', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(164, 'KRA_Form_Received', 'KRA_Form_Received', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(165, 'KRA_form_Received_as_Under_Process_(UP)', 'KRA_form_Received_as_Under_Process_(UP)', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(166, 'CKYC', 'CKYC', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(167, 'Nest_Enable', 'Nest_Enable', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(168, 'Vat_No._Opted', 'Vat_No._Opted', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(169, 'Print_Statement', 'Print_Statement', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(170, 'Research_Pack', 'Research_Pack', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(171, 'Settlement_Type', 'Settlement_Type', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(172, 'ECN_Written_Consent', 'ECN_Written_Consent', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(173, 'App_status', 'App_status', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(174, 'Update_status', 'Update_status', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(175, 'AgencyCode', 'AgencyCode', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(176, 'Exchange Name', 'Exchange Name', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(177, 'Segment Name', 'Segment Name', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(178, 'Techexcel exchange id', 'Techexcel exchange id', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(179, 'Languages', 'Languages', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in'),
(180, 'KRAErrorCode', 'KRAErrorCode', '', '', '', '', '', '', '', '', '', '',NOW(),NOW(), 'thineshgunal.v@fcsonline.co.in', 'sowmiya.l@fcsonline.co.in');